name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}


    steps:
    - uses: actions/checkout@v3

    # node.js 사용
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - run: npm ci # package-lock.json 에 적혀있는 패키지 설치
    - run: npm run build # package.json에 빌드 스크립트
    
    # publish_dir에 들어있는 파일들을 gh-pages 브랜치에 올려줍니다.
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./assets

